name: tdd_clean
description: "A TDD Clean Architecture Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  http: ^1.2.2
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.4
  intl: ^0.20.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.14

flutter:
  uses-material-design: true